name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: swiftc -O -o /tmp/snag Sources/*.swift
